### ISSUE TITLE
Toasts can close prematurely due to ID collision

### ISSUE THREAD

**Issue by fbonetti** [pablen/toasty#1]
**Steps to reproduce:**

1. Open the [demo](http://pablen-toasty-demo.surge.sh/)
2. Press the 's' key to create a success toast
3. Wait 3 seconds
4. Click on the toast to dismiss it
5. Press the 's' key again to create a new success toast
6. The newly created toast will close after 2 seconds instead of 5. This happens because the newly created toast has the same `Id` as the dismissed toast, and the dismissed toast's `Process.sleep` was never killed.

**Possible solutions:**

* When a toast is added, use `Process.spawn` to keep track of the `Process.sleep` process ID. If the user manually dismisses a toast, kill the sleep process with `Process.kill`.
* Use a random number generator to assign a unique ID to each toast. It won't prevent all collisions but the chance of collision will be extremely small.

**Comment by pablen** [comment]
Good catch! thanks, I'll work on it.

**Comment by fbonetti** [comment]
[I opened a PR that implements the second solution](https://github.com/pablen/toasty/pull/2). Let me know what you think!

**Comment by pablen** [comment]
Thanks! I'll take a look in a while.
Was trying your first suggestion last night and failed :(, can't get to work with processes ids (just a beginner here), but it feels like the right approach!

**Comment by fbonetti** [comment]
I agree - killing the process does feel like the approach since it eliminates the chance of collision. I'll see if I can get it to work and open a separate PR.

**Comment by pablen** [comment]
Ok, thanks again for your help!
Nevertheless I just merged your first PR as it is more robust than my previous version.
