### ISSUE TITLE
Demo does not work on mobile

### ISSUE THREAD

**Issue by JordyMoos** [pablen/toasty#3]
In your demo i am forced to hit a keyboard key to create the toasts.
But that is a hard thing to do on mobile.

Can the demo additionally get some buttons that spawn the toasts?

Cheers

**Comment by pablen** [comment]
Sure! I'll add them. Thanks for the feedback.

**Comment by pablen** [comment]
Done. The demo is now usable on mobile!
Default toasts styling looks pretty decent on an iPhone 5 too :)

**Comment by JordyMoos** [comment]
Thank you!
