### ISSUE TITLE
Ability to conditionally show toasts

### ISSUE THREAD

**Issue by smucode** [pablen/toasty#5]
We're using toasty to notify the user whenever API requests are slower than a given threshold. Using the current version of toasty there isn't a way to figure out if a toast is visible or not. If multiple API's are slow and hit the threshold at or around the same time, multiple toasts (in our case with the same contents) are shown.

The most pressing issue we have is to figure out if a given toast is visible or not. If it's the case that one already is visible, we don't want to show another toast as we've already told the user that one or more of the API's are slow. 

Currently we've forked Toasty and exposed the Stack constructors so we can poke around in the toasty internals and figure out if we should show a new toast or not. Simply exposing the constructors as we have, doesn't seem like a good idea for the library to do. I'm not sure what the best approach would be to solve this? I'm happy to submit a MR given I can wrap my head around what a good approach would be.

Further enhancements is to be able to prolong the duration of a given toast, as well as change the contents of the visible toast. Then we can make sure the relevant toast stays visible as new API requests hit the threshold. And we could update the message with the number of pending API requests. But these are enhancements, not strictly needed for us to use Toasty.

**Comment by pablen** [comment]
Hi! thanks for using Toasty :)
I'll think a bit about how I would approach such requirements this week and hopefully I come up with something and let you know.
In general I tried to keep the library model agnostic and hide all the internals behind an opaque Stack type, so advanced features that require access to internals might not be possible at the time. 
Maybe the config model could be extended in a new version to let the user define a function with signature `hasToast toast : a -> Bool` that can check if a specific toast is present in the Stack... something like that?

**Comment by pablen** [comment]
Hi again!
I've just published version 1.1.0 which exports a few more utility functions such as `hasToast`, `addToastIf` and `addToastIfUnique` which I think will help you with your first requirement, e.g. [`addToastIfUnique`](http://package.elm-lang.org/packages/pablen/toasty/1.1.0/Toasty#addToastIfUnique) works just as `addToast` but will automatically avoid duplicates for you. 

You can checkout the [demo](http://pablen-toasty-demo.surge.sh/), and also the documentation is updated. :)

I've been thinking a bit about the other enhancements but I think they're not trivial. If you want to give it a try I would suggest you follow the same approach of exporting helper functions that could be piped  in your `update` function like it's done with `addToast`. Maybe a `replaceToast` would do the trick?

**Comment by smucode** [comment]
Awesome, `addToastIfUnique` works great for our usecase, thanks!
